name: todo_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0


environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:

  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.2.2
  get: ^4.6.6
  intl: ^0.19.0
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  simple_gradient_text: ^1.3.0
  smooth_page_indicator: ^1.2.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_localizations:
    sdk: flutter




flutter:
  fonts:
    - family: Nunito Bold
      fonts:
        - asset: assets/fonts/Nunito-Bold.ttf
    - family: Nunito Normal
      fonts:
        - asset: assets/fonts/Nunito-Medium.ttf
    - family: Nunito Light
      fonts:
        - asset: assets/fonts/Nunito-Light.ttf


  uses-material-design: true

  assets:
    - assets/
    - assets/images/
